language: rust

cache: cargo
services:
  - docker

script:
- cargo check --release
- cargo test

after_success:
- docker run --rm --user "$(id -u)":"$(id -g)" -v "$PWD":/usr/src/myapp -w /usr/src/myapp jsenon/docker-rustfmt:latest cargo fmt
- docker build -t jsenon/sample-actix-server .
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push jsenon/sample-actix-server:latest
