apiVersion: skaffold/v1beta4
kind: Config
build:
  artifacts:
  - image: docker.io/jsenon/sample-actix-server
  local:
      push: true
      useDockerCLI: false
      useBuildkit: false
deploy:
  kubectl:
    manifests:
    - ./kubernetes/*
